#!/bin/csh

#$ -M xli26@nd.edu	 # Email address for job notification
#$ -m e			 # Send mail when job begins, ends and aborts
#$ -pe smp 1		 # Specify parallel environment and legal core size
#$ -q long	 	 # Specify queue
#$ -N CVFESCPU_Fluid	 # Specify job name
##$ -t 1-9:2	         # Specify number of tasks in array

setenv OMP_NUM_THREADS 1

python3 main.py -f cfg/lcMesh.cfg # Application to execute
